# Generated by Django 6.0.2 on 2026-03-25 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoceIndice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voce_indice', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationWSProtocollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_id', models.CharField(max_length=125)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('protocollo_uo', models.CharField(choices=[('', '-')], max_length=12, verbose_name='UO')),
                ('protocollo_uo_rpa', models.CharField(blank=True, default='', help_text='Nominativo RPA', max_length=255, verbose_name='RPA')),
                ('protocollo_uo_rpa_username', models.CharField(blank=True, default='', help_text='Username RPA sul sistema di protocollo', max_length=255, verbose_name='RPA username')),
                ('protocollo_uo_rpa_matricola', models.CharField(blank=True, default='', help_text='Matricola RPA sul sistema di protocollo', max_length=255, verbose_name='RPA matricola')),
                ('protocollo_send_email', models.BooleanField(default=True, verbose_name='Invia e-mail a RPA')),
                ('protocollo_email', models.EmailField(blank=True, help_text='default: settings.PROTOCOL_EMAIL_DEFAULT', max_length=255, null=True, verbose_name='E-mail')),
                ('protocollo_cod_titolario', models.CharField(choices=[('', '-')], max_length=12, verbose_name='Codice titolario')),
                ('protocollo_fascicolo_numero', models.CharField(blank=True, default='', max_length=255, verbose_name='Fascicolo numero')),
                ('protocollo_fascicolo_anno', models.IntegerField(blank=True, null=True, verbose_name='Fascicolo anno')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Configurazione WS Protocollo Categoria',
                'verbose_name_plural': 'Configurazioni WS Protocollo Categorie',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CredentialWSProtocollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=125)),
                ('name', models.CharField(max_length=255, verbose_name='Denominazione configurazione')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('protocollo_username', models.CharField(max_length=255, verbose_name='Username')),
                ('protocollo_password', models.CharField(max_length=255, verbose_name='Password')),
                ('protocollo_aoo', models.CharField(max_length=12, verbose_name='AOO')),
                ('protocollo_agd', models.CharField(blank=True, default='', max_length=12, verbose_name='AGD')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Configurazione WS Protocollo Struttura',
                'verbose_name_plural': 'Configurazioni WS Protocollo Strutture',
                'ordering': ['-created'],
            },
        ),
    ]
