# Generated by Django 6.0.2 on 2026-04-15 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulus_utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationWSProtocolloCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('protocollo_uo', models.CharField(choices=[('', '-')], max_length=12, verbose_name='UO')),
                ('protocollo_persona', models.CharField(blank=True, default='', max_length=255, verbose_name='Nominativo CC')),
                ('protocollo_persona_username', models.CharField(blank=True, default='', max_length=255, verbose_name='Username CC')),
                ('protocollo_persona_matricola', models.CharField(blank=True, default='', max_length=255, verbose_name='Matricola CC')),
                ('configurazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_list', to='titulus_utility.configurationwsprotocollo')),
            ],
            options={
                'verbose_name': 'Destinatario CC Configurazione WS Protocollo',
                'verbose_name_plural': 'Destinatari CC Configurazioni WS Protocollo',
                'ordering': ['created'],
            },
        ),
    ]
