# Generated by Django 6.0.2 on 2026-04-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulus_utility', '0002_configurationwsprotocollocc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repertorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repertorio', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='voceindice',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
