# Generated by Django 6.0.2 on 2026-04-28 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulus_utility', '0003_repertorio_voceindice_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationWSProtocolloOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('protocollo_uo', models.CharField(choices=[('', '-')], max_length=12, verbose_name='UO')),
                ('protocollo_persona', models.CharField(blank=True, default='', max_length=255, verbose_name='Nominativo OP')),
                ('protocollo_persona_username', models.CharField(blank=True, default='', max_length=255, verbose_name='Username OP')),
                ('protocollo_persona_matricola', models.CharField(blank=True, default='', max_length=255, verbose_name='Matricola OP')),
                ('configurazione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='op_user', to='titulus_utility.configurationwsprotocollo')),
            ],
            options={
                'verbose_name': 'Operatore Configurazione WS Protocollo',
                'verbose_name_plural': 'Operatori Configurazioni WS Protocollo',
                'ordering': ['created'],
            },
        ),
    ]
