"""
Django settings for dj-titulus-utility project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os

from .localsettings import *
from pathlib import Path





# Application definition

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dj-titulus-utility.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'DEBUG').upper()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    # 2. FORMATTERS
    'formatters': {
        'docker': {
            # Formato: [Data] Livello [NomeLogger] [File:Riga] Messaggio
            'format': '[{asctime}] {levelname} [{name}] [{filename}:{lineno} in {funcName}] {message}',
            'style': '{',
            'datefmt': '%d/%b/%Y %H:%M:%S',  # Esempio: 11/Dec/2025 12:00:00
        },
    },

    # 3. HANDLERS
    'handlers': {
        'console': {
            'level': LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'docker',  # Selezioniamo il formatter creato sopra
        },
    },

    # 4. LOGGERS
    'loggers': {
        # Configurazione per Django stesso (DB, richieste, sicurezza)
        'django': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        # ROOT LOGGER: Cattura tutto ciò che non è 'django'
        # (inclusa la tua app e librerie terze come requests, boto3, ecc.)
        '': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
        },
    },
}
